language: cpp
compiler:
  - gcc
before_install:
  - sudo apt-get install nasm 
script:
  - cd src
  - make all
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a958ef1caf3ecf95ca40
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
